import React from 'react';
import { useParams, Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, Download, Share2, AlertTriangle, CheckCircle, Clock } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { apiService } from '../services/api';

const ReportView: React.FC = () => {
  const { policyId } = useParams<{ policyId: string}>();
  const { data: report, isLoading, error } = useQuery({
    queryKey: ['report', policyId],
    queryFn: () => apiService.getReport(policyId!),
    enabled: !!policyId,
  });

  const handleExport = () => {
    if (!report) return;
    
    const reportContent = `
POLICY ANALYSIS REPORT
${'='.repeat(50)}

Policy Title: ${report.policy_title || 'N/A'}
Grade: ${report.overall_grade || 'N/A'}
Score: ${(report.overall_score || 0).toFixed(2)}/10
Analysis Date: ${new Date(report.generated_at).toLocaleString()}

EXECUTIVE SUMMARY
${'-'.repeat(20)}
${report.final_synthesis || 'No summary available'}

POLICY STRENGTHS
${'-'.repeat(20)}
${report.strengths?.map((s: string, i: number) => `${i + 1}. ${s}`).join('\n') || 'None listed'}

RECOMMENDATIONS FOR IMPROVEMENT
${'-'.repeat(35)}
${report.weaknesses?.map((w: string, i: number) => `${i + 1}. ${w}`).join('\n') || 'None listed'}

SPECIALIST ANALYSIS
${'-'.repeat(20)}
${report.agent_reports?.map((agent: any) => `\n${agent.agent_name} (${agent.agent_role})\nRisk Score: ${agent.risk_score}/10\nAnalysis: ${agent.analysis}\n`).join('\n') || 'No agent reports available'}

IMPLEMENTATION STRATEGY
${'-'.repeat(25)}
${report.implementation_roadmap || 'No roadmap available'}

Generated by PolicyNet AI Analysis Platform
`;
    
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `policy-analysis-${report.policy_title?.replace(/[^a-zA-Z0-9]/g, '-') || policyId}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-center">
          <Clock className="h-12 w-12 text-blue-600 mx-auto mb-4 animate-spin" />
          <p className="text-gray-600">Loading report...</p>
        </div>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-center">
          <AlertTriangle className="h-12 w-12 text-red-600 mx-auto mb-4" />
          <p className="text-gray-600">Report not found</p>
          <Link to="/" className="text-blue-600 hover:text-blue-700 mt-2 inline-block">Back to Dashboard</Link>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto p-6 space-y-6">
      {/* Header */}
      <div className="bg-white rounded-lg shadow-sm border p-6">
        <div className="flex items-center justify-between mb-4">
          <Link to="/reports" className="flex items-center text-blue-600 hover:text-blue-700">
            <ArrowLeft className="h-4 w-4 mr-1" />
            Back to Reports
          </Link>
          <div className="flex space-x-2">
            <button 
              onClick={handleExport}
              className="flex items-center px-3 py-2 text-sm border rounded-md hover:bg-gray-50"
            >
              <Download className="h-4 w-4 mr-1" />
              Export
            </button>
            <button className="flex items-center px-3 py-2 text-sm border rounded-md hover:bg-gray-50">
              <Share2 className="h-4 w-4 mr-1" />
              Share
            </button>
          </div>
        </div>
        
        <h1 className="text-3xl font-bold text-gray-900 mb-4">{report.policy_title}</h1>
        <div className="flex items-center space-x-6">
          <div className={`px-4 py-2 rounded-lg font-semibold text-lg ${
            report.overall_grade === 'A' ? 'bg-green-100 text-green-800' :
            report.overall_grade === 'B' ? 'bg-blue-100 text-blue-800' :
            report.overall_grade === 'C' ? 'bg-yellow-100 text-yellow-800' :
            report.overall_grade ? 'bg-red-100 text-red-800' : 'bg-gray-100 text-gray-800'
          }`}>
            Grade {report.overall_grade || 'N/A'}
          </div>
          <div className="text-gray-600">
            <span className="text-2xl font-bold text-gray-900">{(report.overall_score || 0).toFixed(2)}</span>
            <span className="text-sm">/10 Overall Score</span>
          </div>
          <div className="text-sm text-gray-500">
            Analysis completed on {new Date(report.generated_at).toLocaleDateString()} at {new Date(report.generated_at).toLocaleTimeString()}
          </div>
        </div>
      </div>

      {/* Executive Summary */}
      <div className="bg-white rounded-lg shadow-sm border p-6">
        <h2 className="text-2xl font-semibold text-gray-900 mb-4">Executive Summary</h2>
        <div className="prose max-w-none text-gray-700">
          <ReactMarkdown>{report.final_synthesis}</ReactMarkdown>
        </div>
      </div>

      {/* Key Insights Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="bg-white rounded-lg shadow-sm border p-6">
          <h3 className="text-lg font-semibold text-green-700 mb-4">Policy Strengths</h3>
          <ul className="space-y-2">
            {report.strengths?.map((strength: string, index: number) => (
              <li key={index} className="flex items-start">
                <CheckCircle className="h-4 w-4 text-green-600 mr-2 mt-0.5 flex-shrink-0" />
                <span className="text-sm text-gray-700">{strength}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="bg-white rounded-lg shadow-sm border p-6">
          <h3 className="text-lg font-semibold text-red-700 mb-4">Recommendations for Improvement</h3>
          <ul className="space-y-2">
            {report.weaknesses?.map((weakness: string, index: number) => (
              <li key={index} className="flex items-start">
                <AlertTriangle className="h-4 w-4 text-red-600 mr-2 mt-0.5 flex-shrink-0" />
                <span className="text-sm text-gray-700">{weakness}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Specialist Analysis */}
      <div className="bg-white rounded-lg shadow-sm border p-6">
        <h2 className="text-2xl font-semibold text-gray-900 mb-6">Specialist Analysis Reports</h2>
        <div className="space-y-6">
          {report.agent_reports?.map((agentReport: any, index: number) => (
            <div key={index} className="border-l-4 border-blue-500 pl-4">
              <div className="flex items-center justify-between mb-3">
                <div>
                  <h3 className="font-semibold text-gray-900 text-lg">{agentReport.agent_name}</h3>
                  <p className="text-sm text-blue-600 font-medium">{agentReport.agent_role}</p>
                </div>
                <div className="text-right">
                  <div className={`px-3 py-1 rounded-full text-sm font-medium ${
                    agentReport.risk_score <= 3 ? 'bg-green-100 text-green-800' :
                    agentReport.risk_score <= 6 ? 'bg-yellow-100 text-yellow-800' :
                    'bg-red-100 text-red-800'
                  }`}>
                    Risk: {agentReport.risk_score}/10
                  </div>
                </div>
              </div>
              <div className="prose max-w-none mb-3">
                <ReactMarkdown>{agentReport.analysis}</ReactMarkdown>
              </div>
              
              {agentReport.recommendations?.length > 0 && (
                <div className="mb-4">
                  <h4 className="font-medium text-gray-900 mb-2">Key Recommendations:</h4>
                  <ul className="space-y-2">
                    {agentReport.recommendations.map((rec: string, recIndex: number) => (
                      <li key={recIndex} className="flex items-start">
                        <CheckCircle className="h-4 w-4 text-blue-600 mr-2 mt-0.5 flex-shrink-0" />
                        <span className="text-sm text-gray-700">{rec}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
              
              {agentReport.data_sources?.length > 0 && (
                <div className="mt-3 pt-3 border-t border-gray-200">
                  <p className="text-xs text-gray-500 font-medium mb-1">Data Sources Used:</p>
                  <div className="flex flex-wrap gap-1">
                    {agentReport.data_sources.map((source: string, sourceIndex: number) => (
                      <span key={sourceIndex} className="text-xs bg-gray-100 text-gray-600 px-2 py-1 rounded">
                        {source}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Implementation Strategy */}
      <div className="bg-white rounded-lg shadow-sm border p-6">
        <h2 className="text-2xl font-semibold text-gray-900 mb-4">Implementation Strategy & Roadmap</h2>
        <div className="prose max-w-none">
          <ReactMarkdown>{report.implementation_roadmap}</ReactMarkdown>
        </div>
      </div>
    </div>
  );
};

export default ReportView;